@base_url=http://127.0.0.1:9001

### GET
GET {{base_url}}

### === HELLO WORLD
###
GET {{base_url}}/v1/hello-world

### path
GET {{base_url}}/v1/hello-world/path/tess

### query
GET {{base_url}}/v1/hello-world/query?message=teewww

### payload
POST {{base_url}}/v1/hello-world/payload
Content-Type: application/json

{
    "message": "okeyas"
}

### error
GET {{base_url}}/v1/hello-world/error/500