@base_url="http://127.0.0.1:9001"

### GET
curl -X GET --location {{base_url}}

### === HELLO WORLD
###
curl -X GET --location {{base_url}}/v1/hello-world

### path
curl -X GET --location {{base_url}}/v1/hello-world/path/tess

### query
curl -X GET --location {{base_url}}/v1/hello-world/query?message=teewww

### payload
curl -X POST --location {{base_url}}/v1/hello-world/payload
Content-Type: application/json

{
    "message": "okeyas"
}

### error
curl -X GET --location {{base_url}}/v1/hello-world/error/500